# Generated by Django 3.0.4 on 2020-04-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, default='none', max_length=80),
        ),
    ]
