# Generated by Django 3.0.4 on 2020-04-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200409_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
