# Generated by Django 3.0.4 on 2020-04-09 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200409_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('project_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
