# Generated by Django 3.0.4 on 2020-04-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200409_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
