# Generated by Django 3.0.4 on 2020-04-09 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('clients', '0006_auto_20200409_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Platform'),
        ),
    ]
